### ISSUE TITLE
new qsign-server

### ISSUE THREAD

**Issue by kaiserverkcraft** [ShintoKosei/qsign-server-list#1]
地址：http://server.kaivps.cloud:18651/
运营商：移动
地址：中国北京
qsign版本：1.1.3

**Comment by kaiserverkcraft** [comment]
密钥：114514 （默认密钥）

**Comment by kaiserverkcraft** [comment]
忘记附上配置了：Intel Xeon E5-2696v4双路 256GB物理机 我这机子大概也就网络不行了（总上传100Mbps）

**Comment by ShintoKosei** [comment]
已添加
